import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import MantineProvider from "@/app/libs/MantineProvider";
import {ColorSchemeScript} from "@mantine/core";
import NextSessionProvider from "@/app/libs/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8"/>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      />
      <title>My awesome app</title>

      <ColorSchemeScript/>
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <MantineProvider>
      <NextSessionProvider>
        {children}
      </NextSessionProvider>
    </MantineProvider>
    </body>
    </html>
  );
}
